import { FlatDetails } from "./types";

// import { v4 as uuidv4 } from "uuid";
export const flats: FlatDetails[] = [
  {
    id: "1",
    price: "40",
    name: "Квартира в классическом стиле и старинной мебелью",
    area: "50",
    roomCount: "2",
    floor: "2",
    maxFloor: "3",
    sleepingCount: "2",
    gallery: [
      "/images/flats/flat-1/1.jpg",
      "/images/flats/flat-1/2.jpg",
      "/images/flats/flat-1/3.jpg",
    ],
    adress: "ул. Фикрета Амирова, 1",
    viewFromWindow: "одно окно во двор, второе на улицу",
    description: `Квартира расположена в центре, в престижном районе города, с красивым видом на город и море.В шаговой доступности множество достопримечательностей-приморский бульвар, парки, скверы, различные кафе, рестораны. Недалеко от дома т/ц "port-baku mall", супермаркеты "24 часа" и другие магазины, где можно порадовать себя и своих близких приятными покупками. От дома до "старого города", "девичьей башни" и "площади фонтанов" можно добраться пешком за 20 минут, прогуливаясь по набережному бульвару.Бизнес-центры "landmark", "port baku", отели "hilltonn", "marriott absheron", торговый центр "park bulvar" находятся недалеко от дома.Прекрасная локация, уютная, просторная квартира со всеми удобствами для комфортного проживания и отдыха!`,
    sleepCountDetails: "1 диван-кровать, 1 односпальная кровать",
    longitude: 40.37557920792142,
    latitude: 49.85140900000209,
    conveniences: {
      main: {
        hasLift: false,
        hasParking: true,
        hasConditioner: true,
        hasTV: true,
        hasWiFi: true,
        hasTextile: true,
        hasLaundry: true,
        hasIron: true,
      },
      kitchen: {
        hasKettle: true,
        hasFridge: true,
        hasGasStove: true,
        hasMicrowave: false,
        hasTableWare: true,
      },
      toilet: {
        hasHairDryer: true,
        hasShower: true,
        hasSlippers: true,
        hasToiletries: true,
      },
    },
  },
  {
    id: "2",
    price: "40",
    name: "Квартира в классическом стиле и старинной мебелью",
    area: "50",
    roomCount: "3",
    floor: "2",
    maxFloor: "3",
    sleepingCount: "3",
    gallery: [
      "/images/flats/flat-1/1.jpg",
      "/images/flats/flat-1/2.jpg",
      "/images/flats/flat-1/3.jpg",
    ],
    adress: "ул. Фикрета Амирова, 1",
    viewFromWindow: "одно окно во двор, второе на улицу",
    description: `Квартира расположена в центре, в престижном районе города, с красивым видом на город и море.В шаговой доступности множество достопримечательностей-приморский бульвар, парки, скверы, различные кафе, рестораны. Недалеко от дома т/ц "port-baku mall", супермаркеты "24 часа" и другие магазины, где можно порадовать себя и своих близких приятными покупками. От дома до "старого города", "девичьей башни" и "площади фонтанов" можно добраться пешком за 20 минут, прогуливаясь по набережному бульвару.Бизнес-центры "landmark", "port baku", отели "hilltonn", "marriott absheron", торговый центр "park bulvar" находятся недалеко от дома.Прекрасная локация, уютная, просторная квартира со всеми удобствами для комфортного проживания и отдыха!`,
    sleepCountDetails: "1 диван-кровать, 1 односпальная кровать",
    longitude: 40.37557920792142,
    latitude: 49.85140900000209,
    conveniences: {
      main: {
        hasLift: false,
        hasParking: true,
        hasConditioner: true,
        hasTV: true,
        hasWiFi: true,
        hasTextile: true,
        hasLaundry: true,
        hasIron: true,
      },
      kitchen: {
        hasKettle: true,
        hasFridge: true,
        hasGasStove: true,
        hasMicrowave: false,
        hasTableWare: true,
      },
      toilet: {
        hasHairDryer: true,
        hasShower: true,
        hasSlippers: true,
        hasToiletries: true,
      },
    },
  },
  {
    id: "3",
    price: "40",
    name: "Квартира в классическом стиле и старинной мебелью",
    area: "50",
    roomCount: "1",
    floor: "2",
    maxFloor: "3",
    sleepingCount: "1",
    gallery: [
      "/images/flats/flat-1/1.jpg",
      "/images/flats/flat-1/2.jpg",
      "/images/flats/flat-1/3.jpg",
    ],
    adress: "ул. Фикрета Амирова, 1",
    viewFromWindow: "одно окно во двор, второе на улицу",
    description: `Квартира расположена в центре, в престижном районе города, с красивым видом на город и море.В шаговой доступности множество достопримечательностей-приморский бульвар, парки, скверы, различные кафе, рестораны. Недалеко от дома т/ц "port-baku mall", супермаркеты "24 часа" и другие магазины, где можно порадовать себя и своих близких приятными покупками. От дома до "старого города", "девичьей башни" и "площади фонтанов" можно добраться пешком за 20 минут, прогуливаясь по набережному бульвару.Бизнес-центры "landmark", "port baku", отели "hilltonn", "marriott absheron", торговый центр "park bulvar" находятся недалеко от дома.Прекрасная локация, уютная, просторная квартира со всеми удобствами для комфортного проживания и отдыха!`,
    sleepCountDetails: "1 диван-кровать, 1 односпальная кровать",
    longitude: 40.37557920792142,
    latitude: 49.85140900000209,
    conveniences: {
      main: {
        hasLift: false,
        hasParking: true,
        hasConditioner: true,
        hasTV: true,
        hasWiFi: true,
        hasTextile: true,
        hasLaundry: true,
        hasIron: true,
      },
      kitchen: {
        hasKettle: true,
        hasFridge: true,
        hasGasStove: true,
        hasMicrowave: false,
        hasTableWare: true,
      },
      toilet: {
        hasHairDryer: true,
        hasShower: true,
        hasSlippers: true,
        hasToiletries: true,
      },
    },
  },
];
